cache:
  storage: ../cache
logging:
  level: debug
  groups:
    - manager
network:
  listen:
    - interface: 127.0.0.1@5353
server:
  id: dev
  workers: 1
  rundir: etc/knot-resolver/runtime
  management:
    interface: 127.0.0.1@5000