network:
  interfaces:
    - listen:
        ip: 127.0.0.1
        port: 5353
server:
  workers: 1
  management:
    listen:
      ip: 127.0.0.1
      port: 5001
    log-level: DEBUG
    rundir: integration/run
cache:
  storage: cache

