workers: 1
network:
  listen:
    - interface: 127.0.0.1@53
tunnel-filter:
  enable: true
  file: /home/blcnn.pt # Edit path to NN model
  sensitivity: 10
  threshold: 97
logging:
  level: info
  groups: [tunnel]
