forward:
  - subtree: '.'
    options:
      dnssec: true
      authoritative: false
    servers:
      - address: [2001:148f:fffe::1, 185.43.135.1]
        transport: tls
        hostname: odvr.nic.cz
      - address: [ 192.0.2.1, 192.0.2.2 ]
        transport: tls
        pin-sha256:
          - d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=
          - E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=
  - subtree: 1.168.192.in-addr.arpa
    options:
      dnssec: false
    servers: [ 192.0.2.1@5335 ]
