rundir: /run/knot-resolver
workers: 2
cache:
  storage: /var/cache/knot-resolver
logging:
  level: info
network:
  listen:
    - interface: 127.0.0.1@53
management:
  unix-socket: /run/knot-resolver/kres-api.sock
